import { PrismaClient, QuoteSize, QuoteStatus } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const existing = await prisma.quote.findFirst({
    where: { email: 'demo@buyfromchina.ca' }
  });

  if (existing) {
    console.info('Demo quote already exists, skipping seed.');
    return;
  }

  await prisma.quote.create({
    data: {
      email: 'demo@buyfromchina.ca',
      recipientName: 'Demo Customer',
      addressLine1: '123 Demo Street',
      addressLine2: 'Suite 500',
      city: 'Toronto',
      province: 'ON',
      productURL: 'https://world.taobao.com/item/1234567890.htm',
      postalCode: 'M5V2T6',
      notes: 'Demo quote generated by seed script.',
      size: QuoteSize.MEDIUM,
      referencePrice: 120,
      itemCostCad: 120,
      serviceFeeCad: 14.4,
      shippingCad: 15.99,
      taxCad: 19.17,
      totalCad: 169.56,
      pricingVersion: PRICING_VERSION,
      status: QuoteStatus.SENT
    }
  });

  console.info('Seed data inserted.');
}

const PRICING_VERSION = '2024-10-28';

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
